### ISSUE TITLE
Secondary tabs missing after upgrade to Umbraco 7.10

### ISSUE THREAD

**Issue by Tidmand** [umco/umbraco-stacked-content#45]
Hi,

we use Stacked content in many of our solutions and it really rocks !!

Unfortunately it seems that support for secondary tabs has broken after an upgrade of Umbraco from version 7.7.13 -> 7.10.4 (we're running on Umbraco Cloud).

One of the reasons why we chose Stacked content over Nested content for building blocks on a page is exactly the option of having secondary tabs on the doctypes included.

Here's an example of a doctype and the view when creating/editing inside Stacked content:

![skaermbillede 2018-06-19 kl 11 45 18](https://user-images.githubusercontent.com/4766336/41590177-aac482f4-73b6-11e8-833c-800d97e3b027.png)

![skaermbillede 2018-06-19 kl 11 44 33](https://user-images.githubusercontent.com/4766336/41590198-b904c23e-73b6-11e8-8883-01ed3f7acf15.png)

Do you know about this issue - and do you have a way to get around it? ... or possibly an update to solve it.

Thanks in advance,
Søren, UMAKERS

**Comment by leekelleher** [comment]
Hi @Tidmand, the issue was due to the "Properties" tab being removed in Umbraco v7.8 (replaced with the "Info" tab (which isn't an editable tab).

You'll need to upgrade Inner Content to the latest version, (v1.1.x) (this is a package dependency for Stacked Content).  You can either get it from [Our Umbraco](https://our.umbraco.org/projects/backoffice-extensions/inner-content/) or [NuGet](https://www.nuget.org/packages/Our.Umbraco.InnerContent).

**Comment by Tidmand** [comment]
Wow @leekelleher - that was quick. Sorry that I didn't catch that the issue already had been solved. Keep up the splendid work !!
