### ISSUE TITLE
Nested Content (Umbraco) in Stacked Content

### ISSUE THREAD

**Issue by CodeCheetah** [umco/umbraco-stacked-content#68]
Hi,

I have a nested content with a bunch of properties set as mandatory inside stacked content package. (nuget package v2.0.3) Validation does not kick in and Im able to save the page/content with empty fields.

Any ideas?

Thanks.

**Comment by leekelleher** [comment]
Hi @CodeCheetah, thanks for raising this.

Unfortunately, it's a known issue - which we can not do much about it, sorry.

The same issue applies to all the "nested" content editors, e.g. Nested Content, Stacked Content, DocTypeGridEditor.  @mattbrailsford has given a more detailed answer on the DTGE repo: https://github.com/umco/umbraco-doc-type-grid-editor/issues/114#issuecomment-447024007

Our recommendation is that you make everything non-mandatory and code your views defensively, so that you don't display any items that do not have the required content.

It's not an ideal solution, but it's the simplest. Hope this helps.

**Comment by CodeCheetah** [comment]
Hi Lee, thank you for your prompt response.
